version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # backend:
  #   build: ./BE/Dockerfile
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - MONGODB_URI=mongodb://root:example@mongo:27017/your_db_name?authSource=admin
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - .:/app

volumes:
  mongo_data:
